import { TrainingDay, Attendance, CalendarEvent, TrainingItem } from '@/types';

// 从CSV解析的数据
export const trainingDays: TrainingDay[] = [
  {
    date: '2025-12-29',
    items: [
      // 热身
      {
        id: 'w1-1',
        title: '球操（舉球拉開）',
        duration: 10,
        category: 'warmup',
        startTime: '12:00',
      },
      {
        id: 'w1-2',
        title: '兩個人對打',
        duration: 10,
        category: 'warmup',
        groupSize: 2,
        startTime: '12:10',
      },
      {
        id: 'w1-3',
        title: '跑傳（低100）',
        duration: 20,
        category: 'warmup',
        requirements: '低100',
        startTime: '12:20',
      },
      // 练球
      {
        id: 'p1-1',
        title: '全場接嗆死',
        duration: 20,
        category: 'practice',
        requirements: '20顆*2趟',
        rounds: 2,
        description: '舉球順便練舉',
        startTime: '12:40',
      },
      {
        id: 'p1-2',
        title: '三人聯防',
        duration: 18,
        category: 'practice',
        groupSize: 3,
        requirements: '一舉二攻擊手',
        rounds: 2,
        description: '2分半*2趟',
        startTime: '13:00',
      },
      {
        id: 'p1-3',
        title: '自由攻擊',
        duration: 15,
        category: 'practice',
        startTime: '13:18',
      },
      {
        id: 'p1-4',
        title: '隊形～友誼賽',
        duration: 30,
        category: 'practice',
        startTime: '13:33',
      },
      {
        id: 'p1-5',
        title: '分三隊',
        duration: 30,
        category: 'practice',
        groupSize: 3,
        startTime: '14:03',
      },
      // 体能
      {
        id: 'f1-1',
        title: '分兩隊賽跑',
        duration: 15,
        category: 'fitness',
        groupSize: 2,
        startTime: '14:33',
      },
    ],
  },
  {
    date: '2025-12-30',
    items: [
      // 热身
      {
        id: 'w2-1',
        title: '球操（舉球拉開）',
        duration: 10,
        category: 'warmup',
        startTime: '12:00',
      },
      {
        id: 'w2-2',
        title: '兩個人對打',
        duration: 10,
        category: 'warmup',
        groupSize: 2,
        startTime: '12:10',
      },
      {
        id: 'w2-3',
        title: '兩側壓重心接球',
        duration: 15,
        category: 'warmup',
        requirements: '30顆2組',
        rounds: 2,
        description: '左右兩側不移動接球，球拋慢，蹲著等球',
        startTime: '12:20',
      },
      {
        id: 'w2-4',
        title: '跑傳（低100）',
        duration: 15,
        category: 'warmup',
        requirements: '低100',
        startTime: '12:35',
      },
      {
        id: 'w2-5',
        title: '全部人一起站四個點對角線互傳',
        duration: 10,
        category: 'warmup',
        requirements: '低100',
        description: '打完逆時針到下一個點',
        startTime: '12:50',
      },
      // 练球
      {
        id: 'p2-1',
        title: '全場接嗆死',
        duration: 20,
        category: 'practice',
        requirements: '20顆*2趟',
        rounds: 2,
        description: '舉球算好球數順便練舉 好球數有意義',
        startTime: '13:00',
      },
      {
        id: 'p2-2',
        title: '個防',
        duration: 25,
        category: 'practice',
        requirements: '12好球*2趟',
        rounds: 2,
        description: '接到三米線內，太低太醜的可以攻擊者自行定義',
        startTime: '13:20',
      },
      {
        id: 'p2-3',
        title: '接扣',
        duration: 30,
        category: 'practice',
        groupSize: 4,
        requirements: '8顆/2組',
        description: '視情況開兩邊 三個點輪流扣 兩側可以不要打在手上',
        startTime: '13:45',
      },
      {
        id: 'p2-4',
        title: '接扣修正',
        duration: 10,
        category: 'practice',
        groupSize: 5,
        description: '兩個前排（攻擊）+三個後排（防守+修正） 接扣→修正給前排攻擊',
        startTime: '14:15',
      },
      {
        id: 'p2-5',
        title: '自由攻擊',
        duration: 15,
        category: 'practice',
        startTime: '14:25',
      },
      {
        id: 'p2-6',
        title: '發球',
        duration: 10,
        category: 'practice',
        startTime: '14:40',
      },
      {
        id: 'p2-7',
        title: '分兩道接發',
        duration: 15,
        category: 'practice',
        requirements: '15顆*2',
        rounds: 2,
        startTime: '14:50',
      },
      {
        id: 'p2-8',
        title: '噗累',
        duration: 20,
        category: 'practice',
        startTime: '15:05',
      },
      // 体能
      {
        id: 'f2-1',
        title: '雙人追球',
        duration: 15,
        category: 'fitness',
        groupSize: 2,
        requirements: '10趟',
        rounds: 10,
        startTime: '15:25',
      },
      {
        id: 'f2-2',
        title: '兩人一組 仰臥起坐起來托球',
        duration: 20,
        category: 'fitness',
        groupSize: 2,
        requirements: '25*3',
        rounds: 3,
        description: '接嗆好球數前五名可以20*3',
        startTime: '15:40',
      },
    ],
  },
  {
    date: '2025-12-31',
    items: [
      // 热身
      {
        id: 'w3-1',
        title: '球操（舉球拉開）',
        duration: 10,
        category: 'warmup',
        startTime: '12:00',
      },
      {
        id: 'w3-2',
        title: '兩個人對打',
        duration: 10,
        category: 'warmup',
        groupSize: 2,
        startTime: '12:10',
      },
      {
        id: 'w3-3',
        title: '跑傳（低100）',
        duration: 20,
        category: 'warmup',
        requirements: '低100',
        startTime: '12:20',
      },
      {
        id: 'w3-4',
        title: '全部人一起站四個點對角線互傳',
        duration: 10,
        category: 'warmup',
        requirements: '低100',
        description: '打完逆時針到下一個點',
        startTime: '12:40',
      },
      // 练球
      {
        id: 'p3-1',
        title: '全場接嗆死',
        duration: 20,
        category: 'practice',
        requirements: '20顆*2趟',
        rounds: 2,
        description: '舉球算好球數順便練舉 好球數有意義',
        startTime: '12:50',
      },
      {
        id: 'p3-2',
        title: 'M字',
        duration: 30,
        category: 'practice',
        groupSize: 4,
        requirements: '2趟*2邊',
        rounds: 4,
        description: '四人一組 應該只能開一邊',
        startTime: '13:10',
      },
      {
        id: 'p3-3',
        title: '大球小球',
        duration: 20,
        category: 'practice',
        requirements: '20顆*2趟',
        rounds: 2,
        startTime: '13:40',
      },
      {
        id: 'p3-4',
        title: '自由攻擊',
        duration: 15,
        category: 'practice',
        startTime: '14:00',
      },
      {
        id: 'p3-5',
        title: '發球',
        duration: 10,
        category: 'practice',
        startTime: '14:15',
      },
      {
        id: 'p3-6',
        title: '雙人接發',
        duration: 20,
        category: 'practice',
        groupSize: 6,
        requirements: '25顆',
        description: '一組6、1號位一組5、6號位=2組',
        startTime: '14:25',
      },
      {
        id: 'p3-7',
        title: '四打四',
        duration: 30,
        category: 'practice',
        groupSize: 4,
        description: '三米內算界外版',
        startTime: '14:45',
      },
      {
        id: 'p3-8',
        title: '噗累',
        duration: 20,
        category: 'practice',
        startTime: '15:15',
      },
      // 体能
      {
        id: 'f3-1',
        title: '棒式跳跳跳',
        duration: 10,
        category: 'fitness',
        rounds: 1,
        startTime: '15:35',
      },
      {
        id: 'f3-2',
        title: '遇線折返',
        duration: 15,
        category: 'fitness',
        requirements: '2趟',
        rounds: 2,
        description: '接嗆好球數前五名一趟',
        startTime: '15:45',
      },
    ],
  },
];

export const attendanceData: Attendance[] = [
  // 大一
  { grade: '大一', name: '劉冠妤', days: [true, true, true] },
  { grade: '大一', name: '劉佩茹', days: [true, true, true] },
  { grade: '大一', name: '盧函畦', days: [true, true, true] },
  { grade: '大一', name: '東濬', days: [true, false, false] },
  { grade: '大一', name: '黃俐慈', days: [true, false, false] },
  // 大二
  { grade: '大二', name: '林采穎', days: [true, true, true] },
  { grade: '大二', name: '莊幃傑', days: [true, false, false] },
  { grade: '大二', name: '張亞鈞', days: [true, true, true] },
  { grade: '大二', name: '林安恬', days: [true, true, true] },
  { grade: '大二', name: '蔡米亞', days: [true, true, false] },
  { grade: '大二', name: '劉羿岑', days: [true, true, true] },
  { grade: '大二', name: '鄭安雯', days: [true, true, true] },
  { grade: '大二', name: '黃柏琁', days: [true, true, true] },
  { grade: '大二', name: '林妤娟', days: [true, true, true] },
  // 大三以上
  { grade: '大三以上', name: '郭誌遠', days: [true, true, true] },
  { grade: '大三以上', name: '王中富', days: [true, false, false] },
  { grade: '大三以上', name: '小米', days: [true, true, true] },
  { grade: '大三以上', name: '王傳喜', days: [false, true, true] },
  { grade: '大三以上', name: '陳致霖', days: [false, true, true] },
  { grade: '大三以上', name: '楊幸蓉', days: [false, true, true] },
  { grade: '大三以上', name: '鍾聿晴', days: [true, false, false] },
  { grade: '大三以上', name: '呂科諺', days: [true, true, true] },
  { grade: '大三以上', name: '羽菲', days: [true, false, false] },
  { grade: '大三以上', name: '蔡依宸', days: [false, true, false] },
  { grade: '大三以上', name: '李承璦', days: [false, false, true] },
];

export const calendarEvents: CalendarEvent[] = [
  { date: '2025-12-29', week: 18, dayOfWeek: '一', afternoon: '醫體', isTraining: true },
  { date: '2025-12-30', week: 18, dayOfWeek: '二', afternoon: '醫體', isTraining: true },
  { date: '2025-12-31', week: 18, dayOfWeek: '三', afternoon: '醫體', isTraining: true },
];

